<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Article|null find($id, $lockMode = null, $lockVersion = null)
 * @method Article|null findOneBy(array $criteria, array $orderBy = null)
 * @method Article[] findAll()
 * @method Article[] findBy(array $criteria, array $orderBy = null , $limit = null , $offset = null )
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
