<?php
namespace AppBundle\Repository;
use AppBundle\Entity\Tags;
/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Tags|null find($id, $lockMode = null, $lockVersion = null)
 * @method Tags|null findOneBy(array $criteria, array $orderBy = null)
 * @method Tags[] findAll()
 * @method Tags[] findBy(array $criteria, array $orderBy = null , $limit = null , $offset = null )
 */
class TagsRepository extends \Doctrine\ORM\EntityRepository
{
}
